---
- key: feedbin-mini
  name: Feedbin Mini
  description: A modern, fast news feed reader with a clean interface. Perfect for
    keeping up with your favorite blogs and news sites.
  category: rss
  action: pre-order
  normal_price: 30
  sale_price: 15
  preorder_url: https://buy.stripe.com/00gbKvfijgqybsIaEG
  waitlist_url: https://docs.google.com/forms/d/e/1FAIpQLSdA84mi74Bz1es0OXy8sbiBq6Mozqsa6mpUL7ZX1im9FRIBbQ/viewform?usp=dialog
  subscribe_url:
  faq_path: "/products/feedbin-mini/faq/"
  scm_url: https://github.com/feedbin/feedbin
  featured: true
- key: freshrss
  name: FreshRSS
  description: Take control of your news feed with our hosted RSS reader service.
    No algorithms, no tracking - just the content you choose.
  category: rss
  action: subscribe
  normal_price: 24
  sale_price: 12
  preorder_url:
  screenshot_url: "/products/freshrss/screenshot.webp"
  subscribe_url: https://buy.stripe.com/7sI7ufgmn0rAdAQ9AA
  faq_path: "/products/freshrss/faq/"
  scm_url: https://github.com/freshrss/freshrss
  donation_url: https://liberapay.com/FreshRSS/
  featured: true
- key: karakeep
  name: Karakeep
  description: A classic read-it-later serivce, comparable with Instapaper or Pocket.  A
    great pair with an RSS reader.
  legal: Instapaper is a trademark of Instant Paper, Inc. Pocket is a trademark of
    Mozilla Corporation.
  category: read-it-later
  action: subscribe
  normal_price: 40
  sale_price: 20
  preorder_url:
  subscribe_url: https://buy.stripe.com/cNi5kD5C15Nw57Jbok0Ba0o
  faq_path:
  scm_url: https://github.com/karakeep-app/karakeep
  featured: true
- key: linkding
  name: Linkding
  description: A minimal, fast bookmark manager designed for self-hosting. Privacy-focused
    alternative to commercial bookmark services.
  category: read-it-later
  action: subscribe
  normal_price: 24
  sale_price: 12
  subscribe_url: https://buy.stripe.com/bJecN5e8x1xgfMngIE0Ba0m
  faq_path:
  scm_url: https://github.com/sissbruecker/linkding
  featured: true
- key: matomo-nano
  name: Matomo Nano
  description: A modern analytics platform formerly known as Piwik, comparable with
    Google Analytics.  This Nano offering is perfect for a small blog, shop, or other
    website.
  legal: Google Analytics is a trademark of Google LLC.
  category: analytics
  action: pre-order
  normal_price:
  sale_price: 50
  preorder_url: https://buy.stripe.com/00w3cv0hHb7Q43Fbok0Ba04
  waitlist_url: https://docs.google.com/forms/d/e/1FAIpQLSf0jKoaF23HOziTJwCr4PPqjYCsqa-yKsv1D4LgKTBSKMSd_A/viewform?usp=dialog
  subscribe_url:
  faq_path:
  scm_url: https://github.com/matomo-org/matomo
  featured: true
- key: miniflux
  name: Miniflux
  description: A minimalist and opinionated feed reader.
  category: rss
  action: join waitlist
  normal_price:
  sale_price:
  preorder_url:
  subscribe_url:
  waitlist_url: https://docs.google.com/forms/d/e/1FAIpQLSeNEFwFRUTbWAjDvHvrh6tCMlBDGDAAsiH9OHkxveLzmpEsRA/viewform?usp=header
  faq_path:
  scm_url: https://github.com/miniflux/v2
  featured: false
- key: omnivore
  name: Omnivore
  description: A complete, open source read-it-later solution for serious readers.
    Omnivore offers advanced features like newsletter subscriptions, PDF support,
    and powerful organization tools.
  category: read-it-later
  action: join waitlist
  normal_price:
  sale_price:
  preorder_url:
  subscribe_url:
  faq_path:
  scm_url: https://github.com/omnivore-app/omnivore
  featured: false
- key: readeck
  name: Readeck
  description: A modern bookmark manager and read-it-later app, comparable with Instapaper
    or Pocket.  A great pair with an RSS reader.
  legal: Instapaper is a trademark of Instant Paper, Inc. Pocket is a trademark of
    Mozilla Corporation.
  category: read-it-later
  action: subscribe
  normal_price: 24
  sale_price: 12
  subscribe_url: https://buy.stripe.com/14A7sL9Sha3MdEf8c80Ba0n
  faq_path:
  scm_url: https://codeberg.org/readeck/readeck
  featured: true
- key: shiori
  name: Shiori
  description: A simple and fast bookmark manager designed for self-hosting. Privacy-focused
    alternative to commercial bookmark services.
  category: read-it-later
  action: subscribe
  normal_price: 24
  sale_price: 12
  subscribe_url: https://buy.stripe.com/5kQ4gzc0p3Fo7fReAw0Ba0p
  faq_path:
  scm_url: https://github.com/go-shiori/shiori
  featured: true
- key: shlink-nano
  name: Shlink Nano
  description: A modern, self-hosted URL shortener with analytics and API. Privacy-focused
    alternative to commercial link shorteners.
  category: url-shortener
  action: pre-order
  normal_price: 6
  sale_price: 4
  preorder_url: https://buy.stripe.com/5kQ4gz6G5cbUgQrfEA0Ba07
  waitlist_url: https://docs.google.com/forms/d/e/1FAIpQLScBPNy65pmyfWCtr9UYrG3B2YXymMwgNFEuzXVHNre3efy1TA/viewform?usp=header
  subscribe_url:
  faq_path:
  scm_url: https://github.com/shlinkio/shlink
  featured: true
- key: tiny-tiny-rss
  name: Tiny Tiny RSS
  description: A powerful, self-hostable RSS reader with a strong community.
  category: rss
  action: join waitlist
  normal_price:
  sale_price:
  preorder_url:
  subscribe_url:
  waitlist_url: https://docs.google.com/forms/d/e/1FAIpQLSeNEFwFRUTbWAjDvHvrh6tCMlBDGDAAsiH9OHkxveLzmpEsRA/viewform?usp=header
  faq_path:
  scm_url: https://gitlab.tt-rss.org/tt-rss/tt-rss
  featured: false
- key: wallabag
  name: Wallabag
  description: A classic read-it-later serivce, comparable with Instapaper or Pocket.  A
    great pair with an RSS reader.
  legal: Instapaper is a trademark of Instant Paper, Inc. Pocket is a trademark of
    Mozilla Corporation.
  category: read-it-later
  action: subscribe
  normal_price: 12
  sale_price: 10
  preorder_url:
  subscribe_url: https://buy.stripe.com/14AdR94xX1xg57J3VS0Ba05
  faq_path:
  scm_url: https://github.com/wallabag/wallabag
  featured: true
